"""empty message

Revision ID: 83f73477c6ea
Revises: 7b45942e39bb
Create Date: 2025-01-22 06:31:17.038887

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f73477c6ea'
down_revision = '7b45942e39bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_memory',
    sa.Column('conversation_id', models.StringUUID(), nullable=False),
    sa.Column('app_id', models.StringUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('form_value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('conversation_id', name='form_memory_pkey')
    )
    with op.batch_alter_table('form_memory', schema=None) as batch_op:
        batch_op.create_index('form_memory_idx', ['conversation_id', 'app_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_memory', schema=None) as batch_op:
        batch_op.drop_index('form_memory_idx')

    op.drop_table('form_memory')
    # ### end Alembic commands ###
